#include "Constants.hpp"

void StripSumScatterConfig::SetDefaults() {
  PURE_BEAM_GATE = PURE_BEAM_GATE_S0_S1;

  REACTION_STRIP_MIN = 2;
  REACTION_STRIP_MAX = 15;

  REQUIRE_SMOOTHNESS_END_STRIP = 12;
  REQUIRE_SMOOTHNESS_MAX_STEP = 1.2;

  REAC_JUMP_MIN = 0.1;
  REAC_JUMP_MAX = 2.0;
  END_STRIP_MAX = 1.0;

  PILEUP_THRESHOLD = 1.75;
  NOISE_THRESHOLD = 0.85;

  REJECT_NOISE = kTRUE;
  NOISE_MIN_STRIPS = 1;

  REJECT_PILEUP = kTRUE;
  PILEUP_MIN_STRIPS = 1;

  REJECT_HIGH_STRIP = kFALSE;
  HIGH_STRIP_THRESHOLD = 4.0;

  REJECT_OFFBEAM = kFALSE;
  OFFBEAM_DIST = 0.3;
  OFFBEAM_MIN_STRIPS = 4;

  TRIGGER_NSIGMA = 5.0;
  TRIGGER_CFD_FRAC = 0.30;
  POST_TRIGGER_SUM_STRIPS = 3;
  CLUSTER_SMOOTH_WINDOW = 1;
  SEED_HALF_BINS = 40;

  SAVGOL_HALF = 2;

  TRACES_PER_CLASS = 40;

  MAX_STRIP_SUM_WORKERS = 12;

  X_LO = 1;
  X_HI = 16;

  GATE_STRIP_X = 1;
  GATE_STRIP_Y = 2;
  GATE_NSIGMA_X = 3.5;
  GATE_NSIGMA_Y = 3.5;
  GATE_MIN = 0.0;
  GATE_MAX = 3.0;
  GATE_BINS = 240;

  XMIN = 14;
  XMAX = 26;
  XBINS = 300;
  YMIN = 0;
  YMAX = 20;
  YBINS = 300;

  SAMPLE_MAX_POINTS = 2000000;

  RERUN_SIM = kFALSE;
  CANDIDATE_REAC_STRIP = 3;

  REQUIRE_SMOOTHNESS = kTRUE;
  REQUIRE_GATE_S3_S4 = kFALSE;
  REQUIRE_GATE_S5_S6 = kFALSE;
  SKIP_SAVGOL_PLOTS = kFALSE;
  SCATTER_SAVGOL = kFALSE;
  REQUIRE_STRIP_16_BELOW_BEAM = kFALSE;
  SKIP_CLUSTER_HISTS = kFALSE;
}

DatasetConfig::DatasetConfig() {
  // Data source
  USE_SOLARIS_DATA = kFALSE;
  SOL_SPLIT_CHUNK_SECONDS = 30.0;
  SOL_N_SPLIT_WORKERS = 32;
  N_CHUNKS = -1;

  // Hardware layout
  N_BOARDS = 4;
  N_CHANNELS = 16;
  TIMING_REF_BOARD = 0;

  // Timing
  TIMING_MIN_ENERGY = 0;
  TIMING_MAX_ENERGY = 16384;
  TIMING_OVERLAP_MARGIN_S = 5;
  TIMING_THRESH_DT_US = 150.0;
  TIMING_MAX_ABS_SHIFT_S = 0.25;
  TIMING_SHIFT_COARSE_STEP_US = 1000.0;
  TIMING_SHIFT_FINE_STEP_US = 0.5;
  TIMING_SHIFT_FINE_HALF_WIDTH_US = 1000.0;
  TIMING_SHIFT_MIN_NPTS = 10;
  TIMING_SHIFT_MAX_SCAN_CANDIDATES = 2000000;
  TIMING_DO_BOARD_SYNC = kFALSE;
  TIMING_DO_SORT = kFALSE;

  REJECT_FLAGGED_EVENTS = kFALSE;
  REJECT_MULTI_HIT_EVENTS = kFALSE;

  IGNORE_SHORT_STRIPS = kFALSE;
  IGNORE_STRIP_0 = kFALSE;
  IGNORE_STRIP_17 = kFALSE;

  HAS_CATHODE = kTRUE;
  HAS_GRID = kTRUE;
  HAS_STRIP0 = kTRUE;
  HAS_STRIP17 = kTRUE;

  SKIP_EXISTING = kTRUE;
  SAVE_PLOTS = kTRUE;

  SKIP_CALIBRATION = kFALSE;

  SAVE_SAMPLE_TRACES = 0;

  MAX_FUSED_WORKERS = 12;

  REFERENCE_CHANNEL = "Grid";
  EVENT_TIME_WINDOW_US = 8.0;
  DEDUP_STRATEGY = kLARGEST_ENERGY;

  USE_GPU_ACCELERATION = kTRUE;
  MAX_GPU_CONCURRENT_SORTS = 20;

  STRIP_DE_OVERVIEW_MIN_NORMED = 0.8;
  STRIP_DE_OVERVIEW_MAX_NORMED = 5;
  STRIP_DE_MIN_NORMED = 0.8;
  STRIP_DE_MAX_NORMED = 1.3;
  CATHODE_E_MAX_NORMED = 300;
  TOTAL_E_MIN_NORMED = 10.0;
  TOTAL_E_MAX_NORMED = 400.0;

  STRIP_SUM_SCATTER_CONFIG.SetDefaults();

  STRIP_E_MIN_ADC = 0.0;
  STRIP_E_MAX_ADC = 4096.0;
  TOTAL_E_MIN_ADC = 0.0;
  TOTAL_E_MAX_ADC = 60000.0;

  GRID_MIN_ADC = 0.0;
  GRID_MAX_ADC = 16384.0;

  REFERENCE_CHANNEL_MIN_ADC = 0.0;
  REFERENCE_CHANNEL_MAX_ADC = 16384.0;

  STRIP0_MAX_ADC = 16384.0;
  STRIP17_MAX_ADC = 16384.0;
  CATHODE_MAX_ADC = 16384.0;

  LEFT_EVEN_MAX_ADC = 16384.0;
  LEFT_ODD_MAX_ADC = 16384.0;
  RIGHT_EVEN_MAX_ADC = 16384.0;
  RIGHT_ODD_MAX_ADC = 16384.0;
}
